spring:
  application:
    name: eureka #高可用的实例名称要一样， 或者 eureka.instance.hostname 一样
  profiles:
    active: peer_one
security:
  basic:
    enabled: false  #关闭登陆
  user:
    name: admin
    password: admin

---
server:
  port: 8761
spring:
  profiles: peer_one
eureka:
  instance:
    hostname: peer1
    instance-id: ${spring.application.name}:${server.port}
    #prefer-ip-address: true #该值为true,则注册地址可以用 ip,如 http://localhost:8762/eureka/ ，否则请用 hostname
  client:
    register-with-eureka: true #是否注册自身到eureka服务器,eureka单节点不可用
    fetch-registry: true #是否从eureka服务器获取注册信息,eureka单节点不可用
    service-url:
      defaultZone: http://peer2:8762/eureka/,http://peer3:8763/eureka/
  server:
    enable-self-preservation: true #设置为 true eureka的自我保护，实例失效不会删除
    #waitTimeInMsWhenSyncEmpty: 0

---
server:
  port: 8762
spring:
  profiles: peer_two
eureka:
  instance:
    hostname: peer2
    instance-id: ${spring.application.name}:${server.port}
    #prefer-ip-address: true #该值为true,则注册地址可以用 ip,如 http://localhost:8762/eureka/ ，否则请用 hostname
  client:
    register-with-eureka: true #是否注册自身到eureka服务器,eureka单节点不可用
    fetch-registry: true #是否从eureka服务器获取注册信息,eureka单节点不可用
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer3:8763/eureka/
  server:
    enable-self-preservation: true #设置为 true eureka的自我保护，实例失效不会删除
    #waitTimeInMsWhenSyncEmpty: 0

---
server:
  port: 8763
spring:
  profiles: peer_three
eureka:
  instance:
    hostname: peer3
    instance-id: ${spring.application.name}:${server.port}
    #prefer-ip-address: true #该值为true,则注册地址可以用 ip,如 http://localhost:8762/eureka/ ，否则请用 hostname
  client:
    register-with-eureka: true #是否注册自身到eureka服务器,eureka单节点不可用
    fetch-registry: true #是否从eureka服务器获取注册信息,eureka单节点不可用
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  server:
    enable-self-preservation: true #设置为 true eureka的自我保护，实例失效不会删除
    #waitTimeInMsWhenSyncEmpty: 0