server:
  port: 9001
spring:
  application:
    name: hystrix
turbine:
  app-config: bootthree,bootone
  clusterNameExpression: new String("default")
feign:
  hystrix:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer2:8761/eureka/,http://peer3:8762/eureka/,http://peer3:8763/eureka/
management:
  security:
    enabled: false #spring cloud接口权限