server:
  port: 9001
spring:
  application:
    name: hystrix
feign:
  hystrix:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer2:8761/eureka/,http://peer3:8762/eureka/,http://peer3:8763/eureka/